import { readFile, writeFile } from "node:fs/promises";

const src1x = "branding/ui/alu/alu-tile1x.png";
const src2x = "branding/ui/alu/alu-tile2x.png";
const out   = "branding/ui/alu/alu-embed.css";

const b64 = async (p) => (await readFile(p)).toString("base64");

async function main() {
  const [d1, d2] = await Promise.all([b64(src1x), b64(src2x)]);
  const css = `/* Auto-generated by scripts/embed-alu.mjs */
:root {\n  --img-aluminium: image-set(\n    url('data:image/png;base64,${d1}') 1x,\n    url('data:image/png;base64,${d2}') 2x\n  );\n}\n`;
  await writeFile(out, css, { encoding: "utf8" });
  console.log(`Wrote ${out} (aluminium tile embed)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

